### ISSUE TITLE
Add [...]Request.cs objects to SpiceDb.Models or remove all and use Authzed.Api.V1 classes

### ISSUE THREAD

**Issue by muntdan** [JalexSocial/SpiceDb#2]
Having methods with a combination of fields and Model objects that are not compatible with Authzed.Api.V1 classes is hard to use.:

` public async IAsyncEnumerable<SpiceDb.Models.LookupResourcesResponse> LookupResources(string resourceType, string permission, ResourceReference subject, Dictionary<string, object>? context = null, ZedToken? zedToken = null, CacheFreshness cacheFreshness = CacheFreshness.AnyFreshness)`

![image](https://user-images.githubusercontent.com/105269340/219649303-bbbc6e1b-7ec4-4d08-b69a-065c61a86c6c.png)

SpiceDbClient.LookupResources() method does not accept/have a LookupResourcesRequest object from SpiceDb.Models nor does accept the Authzed.Api.V1.LookupResourcesRequest object.
Also if you decide to have your own in SpiceDb.Models, maybe name them a bit differently (Eg: LookupResourcesReq instead of LookupResourcesRequest, LookupResourcesRes instead of LookupResourcesResponse, etc)

**Comment by tanczosm** [comment]
Next I'll be adding unit tests and validating the correctness of each method.

**Comment by muntdan** [comment]
> The interface is of bigger importance, as I'd like to leave it open to potentially having clients for other implementations of Zanzibar (Keto, Permify, etc). It would require some name changes to refactor but I wanted at least one layer of abstraction from the grpc client.

Thank maybe you should publish 2 Nuggets: SpiceDb.Client and SpiceDb.Wrapper.
Or if you want some others in the future: [Zanzibar|FGA|FineGrainedAccess|RBAC].Wrapper.SpiceDb and [Zanzibar|FGA|FineGrainedAccess|RBAC].Wrapper.SpiceDb.Client.

PS: I havent tested Keto or Permify, but I have tested OpenFGA and compared to SpiceDb. Altotugh they are at V2 and have Auth0 behind, they are still behind (they have bugs in the multiple list of objects retrieval) ..at least 1 month ago they had.

**Comment by tanczosm** [comment]
I'm not keen on doing 2 of these.  If someone wants a plain grpc client they can just grab the proto files and generate one for themselves.  There are some things that I'm adding that are more ease of use issues.

For one, I don't want to be tying all of my code to specific permission system prefixes/slugs.  I'm looking at deploying the same software but with configurable prefix slugs.

So creating a client would now require a slug:
```
var client = new SpiceDbClient(secrets.ServerAddress, secrets.Token, "arch");
```

And then instead of:
```
var bobCanRead = client.CheckPermission(new Permission("arch/document:firstdoc#reader@arch/user:bob"));
```

I want the more generic (although the above would still certainly work):
```
var bobCanRead = client.CheckPermission(new Permission("document:firstdoc#reader@user:bob"));
```

The prefix slug will be attached to the initialized client and every resource/subject type will be enforced to begin with that prefix.  Furthermore, the schema that is imported can come straight out of the Authzed playground and any imported relationships don't need prefixes either.

Then I can completely control the applied schema with a config file.

**Comment by tanczosm** [comment]
Also..

```
client.AddRelationship("document:firstdoc#reader@user:kevin");
```

Creates the relationship `arch/document:firstdoc#reader@arch/user:kevin`

The original API methods are still available but wrapped.  I'm working on the testing fixtures next.
